beacon_endpoint = "https://lodestar-kiln.chainsafe.io"
eth1_endpoint = "https://rpc.kiln.themerge.dev"
path_to_current_sync_committee = "../contract_wrapper/data/next_sync_committee_kiln_period_133.json"
path_to_next_sync_committee = "../contract_wrapper/data/next_sync_committee_kiln_period_134.json"
path_to_execution_blocks_headers = "../contract_wrapper/data/execution_block_headers_kiln_1099394-1099937.json"
path_to_light_client_updates = "../contract_wrapper/data/light_client_updates_kiln_1099394-1099937.json"
path_to_attested_state = "../contract_wrapper/data/beacon_state_kiln_slot_1099459.json"
path_to_finality_state = "../contract_wrapper/data/beacon_state_kiln_slot_1099392.json"
network_name = "kiln"
first_slot = ""
slot_without_block = ""