beacon_endpoint = "https://lodestar-goerli.chainsafe.io" #"https://lodestar-kiln.chainsafe.io"
eth1_endpoint = "https://goerli.infura.io/v3/64aa9edc46d941c3b30882ad2eae4304" #"https://rpc.kiln.themerge.dev"
path_to_current_sync_committee = "./data/goerli_testdata/next_sync_committee_period_473.json" #"../contract_wrapper/data/next_sync_committee_kiln_period_133.json"
path_to_next_sync_committee = "./data/goerli_testdata/next_sync_committee_period_474.json" #"../contract_wrapper/data/next_sync_committee_kiln_period_134.json"
path_to_execution_blocks_headers = "./data/goerli_testdata/execution_block_headers.json" #"../contract_wrapper/data/execution_block_headers_kiln_1099394-1099937.json"
path_to_light_client_updates = "./data/goerli_testdata/light_client_updates.json" #"../contract_wrapper/data/light_client_updates_kiln_1099394-1099937.json"
path_to_attested_state = "./data/goerli_testdata/goerli_state_3885731.json" #"../contract_wrapper/data/beacon_state_kiln_slot_1099459.json"
path_to_finality_state = "./data/goerli_testdata/goerli_state_3885664.json" #"../contract_wrapper/data/beacon_state_kiln_slot_1099392.json"
network_name = "goerli" #"kiln"
first_slot = 3885632
slot_without_block = 3885649
right_bound_in_slot_search = 3885800
left_empty_slot = 3885722
right_empty_slot = 3885723
wasm_filepath = "../../contracts/near/target/wasm32-unknown-unknown/release/eth2_client.wasm" #"../../contracts/near/res/eth2_client.wasm"