---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prover-on-ethereum
  title: "Prover on Ethereum"
  description: |-
    Takes proof of a Receipt from NEAR blockchain and checks if it's valid and included on-chain.
  tags:
    - contract
    - ethereum
  links: []
  annotations:
    aurora.dev/security-tier: "1"
spec:
  owner: bridge-team
  type: contract
  lifecycle: production
  system: bridge-protocol
  deployedAt:
    - contract:ethereum/mainnet/0x051ad3f020274910065dcb421629cd2e6e5b46c4
  interactsWith:
    - contract:ethereum/mainnet/0x3be7df8db39996a837041bb8ee0dadf60f767038
