steps:
    - label: "nearbridge test"
      command: |
          source ~/.nvm/nvm.sh
          source ~/.yarn/yarn.sh
          cd contracts/eth/nearbridge
          yarn
          yarn test
      agents:
          - "queue=medium"

    - label: "nearprover test"
      command: |
          source ~/.nvm/nvm.sh
          source ~/.yarn/yarn.sh
          cd contracts/eth/nearprover
          yarn
          yarn test
      agents:
          - "queue=medium"

    - label: "verify near headers"
      command: |
          source ~/.nvm/nvm.sh
          source ~/.yarn/yarn.sh
          yarn
          cd contracts/eth/
          ci/test_verify_near_headers.sh
      agents:
          - "queue=medium"

    - label: "verify near proofs"
      command: |
          source ~/.nvm/nvm.sh
          source ~/.yarn/yarn.sh
          yarn
          cd contracts/eth/
          ci/test_verify_near_proofs.sh
      agents:
          - "queue=medium"
