steps:
    - label: "linter"
      command: |
          source testing/ci/e2e_ci_prepare_env.sh
          yarn
          yarn standard
          yarn prettier-solidity

      timeout: 5

      agents:
          - "queue=default"

    - label: "e2e"
      command: |
          source testing/ci/e2e_ci_prepare_env.sh
          source testing/ci/e2e_ci_prepare_log.sh
          testing/ci/e2e.sh

      artifact_paths:
          - "logs/**/*.log"
      timeout: 60

      agents:
          - "queue=default"

    - label: "e2e myerc20"
      command: |
          source testing/ci/e2e_ci_prepare_env.sh
          source testing/ci/e2e_ci_prepare_log.sh
          testing/ci/e2e_deploy_contract.sh

      artifact_paths:
          - "logs/**/*.log"
      timeout: 60

      agents:
          - "queue=default"

    - label: "challenge with watchdog"
      command: |
          source testing/ci/e2e_ci_prepare_env.sh
          source testing/ci/e2e_ci_prepare_log.sh
          testing/ci/test_challenge.sh

      artifact_paths:
          - "logs/**/*.log"
      timeout: 60

      agents:
          - "queue=default"

    - label: "test eth-relay catchup"
      command: |
          source testing/ci/e2e_ci_prepare_env.sh
          source testing/ci/e2e_ci_prepare_log.sh
          testing/ci/test_ethrelay_catchup.sh

      artifact_paths:
          - "logs/**/*.log"
      timeout: 60

      agents:
          - "queue=default"

    - label: "contracts/eth/"
      command: buildkite-agent pipeline upload .buildkite/contracts-eth.yml

    - label: "contracts/near/"
      command: buildkite-agent pipeline upload .buildkite/contracts-near.yml
