---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ethereum-light-client-on-near
  description: Ethereum Light Client on NEAR
  tags:
    - contract
    - near
  links: []
  annotations:
    aurora.dev/security-tier: "1"
spec:
  owner: bridge-team
  type: contract
  lifecycle: production
  system: bridge-protocol
  deployedAt:
    - contract:near/mainnet/client.bridge.near
    - contract:near/mainnet/client-eth2.bridge.near
    - contract:near/testnet/client-eth2.goerli.testnet
    - contract:near/testnet/client6.goerli.testnet
  interactsWith:
    - relayer:near/mainnet/relayer.bridge.near
