beacon_endpoint = "http://unstable.sepolia.beacon-api.nimbus.team"
eth1_endpoint = "https://sepolia.infura.io/v3/API_KEY"
path_to_attested_state_for_period = "./data/beacon_state_goerli_slot_5243067.json"
path_to_light_client_update_for_attested_slot = "./data/beacon_light_client_update_goerli_slot_5243067.json"
first_slot = 7585792
eth1_number = 0x77D17F
path_to_block = "./data/beacon_block_sepolia_slot_7585792.json"
path_to_header = "./data/beacon_header_sepolia_slot_7585792.json"
path_to_light_client_update = "./data/beacon_light_client_update_sepolia_period_926.json"
