on:
  push:
    branches:
      - master
      - the-merge
  pull_request:
name: Contracts (NEAR)
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - job-name: build rust contracts
            cmd: |
              cd contracts/near
              make build-eth2-client
            timeout-minutes: 40

          - job-name: test eth2-client
            cmd: |
              cd contracts/near/eth2-client
              ./test.sh
            timeout-minutes: 40

          - job-name: test relayer
            cmd: |
              cd relayer
              rustup target add wasm32-unknown-unknown
              cargo test
            timeout-minutes: 20

    name: ${{ matrix.job-name }}
    steps:
      - name: Install cargo-near
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/latest/download/cargo-near-installer.sh | sh

      - name: Install LFS
        run: sudo apt-get install git-lfs

      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Execute
        env:
          ETH1_INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }} 
        run: ${{ matrix.cmd }}
        timeout-minutes: ${{ matrix.timeout-minutes }}
