on:
  push:
    branches:
      - master
  pull_request:
name: Sigma Prime security testing
jobs:
  sigma-prime:
    runs-on: [self-hosted, heavy]
    name: Sigma Prime security testing
    steps:

      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Clone sigma prime security testing repository
        uses: actions/checkout@v2
        with:
          repository: aurora-is-near/sigma-prime-security-testing
          ssh-key: ${{ secrets.SIGMA_PRIME_REPO_SSH_KEY }}
          path: sigma-prime/tests

      - name: Build docker-image
        run: |
          docker build \
            -f sigma-prime/tests/Dockerfile \
            -t "sigma-prime-testing-${RUNNER_NAME}" \
            ./sigma-prime

      - name: Run tests
        run: |
          docker run \
            --rm \
            -v "$(pwd)/.:/repo/rainbow-bridge" \
            -e SOME_VARIABLE=SOME_VALUE \
            "sigma-prime-testing-${RUNNER_NAME}"

      - name: Remove docker image
        if: ${{ always() }}
        run: docker rmi "sigma-prime-testing-${RUNNER_NAME}" || true
